### ISSUE TITLE
conda-forge package for node v16.13.0

### ISSUE THREAD

**Issue by megasanjay** [conda-forge/nodejs-feedstock#222]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:
Opening an issue to see if there are any updates with the release builds for node version 16.13.0. It would appear that newer versions of webpack are somehow broken on macOS and Linux with v16.12.0. I don't see any issue threads for v16.13 so I'm interested in seeing the status of this version. 

From the other comments I have read, there seems to be an issue with nodejs moving to OpenSSL 3 and I see a failed pr on the list with that title. Is that related to this issue? At the moment, we can switch to nvm instead of conda but would definitely like to see the whole environment on one platform.

**Comment by minrk** [comment]
Thanks for the ping! The regular bump PR for 16 wasn't issued because of the 17 release, so had to do it manually: #224

**Comment by minrk** [comment]
closed by #224
