### ISSUE TITLE
Newer 16.x builds?

### ISSUE THREAD

**Issue by bollwyvl** [conda-forge/nodejs-feedstock#247]
### Comment:

What's the desired process to getting an updated 16.x build? Looks like the [newest](https://nodejs.org/download/release/latest-v16.x/) is up to `16.4.2`. Can we fool `main` to start making PRs, a la #223?

**Comment by minrk** [comment]
Backport branches don't get auto-bumps, so until that's supported we need to do manual version bump PRs to the 16.x branch like #248. I'm not sure the autobot understands version constraints, so it would probably keep trying to bump 16.4 to 17.x if we tried to put 16.x on main.

**Comment by minrk** [comment]
16.14.2 is building now

**Comment by bollwyvl** [comment]
> 16.14.2 is building now

Thanks, that's awesome. 

> branches don't get auto-bumps

Yeah, i've looked into that a bit in the past... it's kinda non-trivial, i guess, without a good deal more metadata. 

near term, i was just wondering if this repo _wasn't_ planning on shipping another 17, if `main` could go back to 16, but i can see how SEVENTEEN IS BIGGER is a pretty clear signal for the bot... noted over on #223 that there might be a clear path forward, though.
