### ISSUE TITLE
Binary lacks internationalization support (ICU)

### ISSUE THREAD

**Issue by dschuessler** [conda-forge/nodejs-feedstock#309]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

The node.js binary does not have internationalization support. Unlike the official node.js binaries, `node -p process.versions.icu` prints `undefined` for the conda-forge binary. This leads to some node software not working as expected. ([Example](https://github.com/nestjs/nest-cli/issues/2086))

What I tried:
* Running `conda config --set channel_priority strict` before installing node.
* Additionally, installing the `icu` package as suggested on the [conda-forge "Tips & tricks" page](https://conda-forge.org/docs/user/tipsandtricks.html).
* Starting node with `NODE_ICU_DATA=envs/default/lib` and `NODE_ICU_DATA=envs/default/icu`.

### Installed packages

```shell
# packages in environment at /Users/xxx/Desktop/demo_app/envs/default:
#
# Name                    Version                   Build  Channel
ca-certificates           2023.01.10           hecd8cb5_0  
icu                       58.2                 h0a44026_3  
krb5                      1.19.4               hdba6334_0  
libcxx                    14.0.6               h9765a3e_0  
libedit                   3.1.20221030         h6c40b1e_0  
libpq                     12.9                 h1c9f633_3  
libuv                     1.44.2               h6c40b1e_0  
ncurses                   6.4                  hcec6c5f_0  
nodejs                    18.15.0              hab5cffc_0  
openssl                   1.1.1t               hca72f7f_0  
postgresql                12.9                 h1c9f633_3  
readline                  8.2                  hca72f7f_0  
zlib                      1.2.13               h4dc903c_0
```

### Environment info

```shell
active environment : /Users/xxx/Desktop/demo_app/envs/default
    active env location : /Users/xxx/Desktop/demo_app/envs/default
            shell level : 2
       user config file : /Users/xxx/.condarc
 populated config files : /Users/xxx/.condarc
          conda version : 23.3.1
    conda-build version : not installed
         python version : 3.10.10.final.0
       virtual packages : __archspec=1=x86_64
                          __osx=10.16=0
                          __unix=0=0
       base environment : /usr/local/Caskroom/miniconda/base  (writable)
      conda av data dir : /usr/local/Caskroom/miniconda/base/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /usr/local/Caskroom/miniconda/base/pkgs
                          /Users/xxx/.conda/pkgs
       envs directories : /usr/local/Caskroom/miniconda/base/envs
                          /Users/xxx/.conda/envs
               platform : osx-64
             user-agent : conda/23.3.1 requests/2.29.0 CPython/3.10.10 Darwin/21.6.0 OSX/10.16
                UID:GID : 501:20
             netrc file : /Users/xxx/.netrc
           offline mode : False
```

**Comment by minrk** [comment]
Strange, it is built with icu support and depends on icu. Must be something off in the linking, I suppose. Or maybe the build configuration.

Question: does it work in nodejs 16.19?

**Comment by dschuessler** [comment]
It turned out that I had not installed node.js from conda-forge in the first place. I did `anaconda-project add-packages nodejs` and mistakenly thought that it defaults to the conda-forge channel. Your binaries are fine.

**Comment by dschuessler** [comment]
I have in fact installed nodejs from the `main` channel and their code explains that internationalization is disabled on purpose: https://github.com/AnacondaRecipes/nodejs-feedstock/blob/27c65d4569fa1d9a377dff0441fbdcaee33a062e/recipe/build.sh#L39

So, if anyone finds this in search for a node.js binary for their conda environment that supports internationalization, install nodejs through the conda-forge channel.
