### ISSUE TITLE
The filename or extension is too long

### ISSUE THREAD

**Issue by lebedov** [conda-forge/nodejs-feedstock#33]
The problem described in #12 appears to have recurred with 9.11.0 on Windows 7:

```
The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    nodejs-9.11.0              |                0        12.6 MB  conda-forge

The following NEW packages will be INSTALLED:

    nodejs: 9.11.0-0 conda-forge

Proceed ([y]/n)? y


Downloading and Extracting Packages
nodejs 9.11.0#######6   |  76%

FileNotFoundError(2, 'The filename or extension is too long')
```

**Comment by minrk** [comment]
@lebedov what is your Python version in your root conda environment?

**Comment by lebedov** [comment]
3.6.5

**Comment by minrk** [comment]
Hm, I thought this bug was fixed by recent Python. The Python bug on this topic: https://bugs.python.org/issue18199

**Comment by minrk** [comment]
What version of conda?

**Comment by lebedov** [comment]
Conda 4.5.1.

**Comment by jakirkham** [comment]
Can you please share `conda info`? Also what is the path of the environment this package is being installed into?

**Comment by jakirkham** [comment]
Could you please share this report in issue ( https://github.com/conda/conda/issues/7203 ), @lebedov?

**Comment by jakirkham** [comment]
This is ultimately a `conda` problem that has been filed as issue ( https://github.com/conda/conda/issues/7203 ). Please follow along and share info there. FWIW there is a [suggested workaround]( https://github.com/conda/conda/issues/7203#issuecomment-390506535 ) for this issue. Going to close to consolidate the discussion in that issue. Thanks for reporting and sharing details.

**Comment by lebedov** [comment]
@jakirkham I encountered the same issue with 9.11.1.
