### ISSUE TITLE
Update v18 to 18.19.0

### ISSUE THREAD

**Issue by therc** [conda-forge/nodejs-feedstock#340]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Version 18.18.2 is not the latest LTS anymore. See 18.19.0 changes:
https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V18.md#18.19.0

### Installed packages

```shell
<immaterial>
```

### Environment info

```shell
<immaterial>
```

**Comment by xhochy** [comment]
Please open a PR that updates it.

**Comment by therc** [comment]
I created https://github.com/conda-forge/nodejs-feedstock/pull/341 but I am not sure if that's all that's needed.

**Comment by therc** [comment]
It's four days, but still no Mac builds?

https://anaconda.org/conda-forge/nodejs/files?version=18.19.0

**Comment by jakirkham** [comment]
Please see this comment: https://github.com/conda-forge/nodejs-feedstock/pull/341#issuecomment-1939295854
