### ISSUE TITLE
Update libuv pinning to >=1.48

### ISSUE THREAD

**Issue by bdice** [conda-forge/nodejs-feedstock#343]
### Comment:

I want to install `nodejs>=20` and `cmake>=3.29` together. However, these have conflicting ranges of `libuv` pinnings. It looks like this can be solved by just making a new build, since `libuv 1.48` was released after the most recent nodejs packages.

**Comment by bdice** [comment]
@conda-forge-admin, please rerender

**Comment by xhochy** [comment]
This should then come in as a migration and not via a manual PR.

**Comment by bdice** [comment]
I don’t think libuv is a part of the core pinnings? The pinning for nodejs seems to be unspecified, it just uses the latest version.

**Comment by bdice** [comment]
Sorry, I reopened #345. I thought #344 was closed because it was a bot PR and not because it was the wrong approach. @xhochy Can you explain what changes you want to see here?
