### ISSUE TITLE
Adding the `node_modules/.bin` to the path in the activation.

### ISSUE THREAD

**Issue by ruben-arts** [conda-forge/nodejs-feedstock#356]
### Comment:

He all,

Would it make sense to add the `node_modules/.bin` path to the actual path on activation of an environment with `nodejs`?

It would allow me to directly execute the binaries installed in the environment by npm without extra configuration. 

Thanks in advance!

**Comment by xhochy** [comment]
It doesn't make se sense as you can activate an environment from anywhere so $PWD/node_modules/.bin is not ensure to be correct.

**Comment by ruben-arts** [comment]
I see, my bad. I was thinking it would locate it into the prefix. But on a second try I see it's indeed going to `pwd`. Closing the issue. Thanks for the response.
