### ISSUE TITLE
branch 20.x doesn't exist

### ISSUE THREAD

**Issue by beckermr** [conda-forge/nodejs-feedstock#363]
The `20.x` branch does not exist but the key here: https://github.com/conda-forge/nodejs-feedstock/blob/main/conda-forge.yml#L5 is causing the bot to choke.

**Comment by jakirkham** [comment]
Adding code snippet for clarity

https://github.com/conda-forge/nodejs-feedstock/blob/ce6d0a6c781de7c1e31bb1e104a2b4df697361a2/conda-forge.yml#L1-L5

Matt is suggesting dropping the last line

@xhochy looks like you added it. Are you ok with dropping or is there something else you would like to do here?

**Comment by xhochy** [comment]
I have added a 20.x branch
