### ISSUE TITLE
NODE_PATH advice/setup/warning post nodejs install?

### ISSUE THREAD

**Issue by cottrell** [conda-forge/nodejs-feedstock#55]
I was hitting problems with "npm i -g ..." libraries not being found when require('..') in node. 

The issue turned out to be NODE_PATH not set. Am wondering if there is a good place to set this automatically in the "activate" methods or whether there should be a warning to do something manually. Could save others some time.

**Comment by minrk** [comment]
Is conda-installed node behaving differently to a standard node install here? I thought global packages weren't generally available when you use `require`, only local packages are found that way. NODE_PATH can be used to break standard env isolation, but I'm not sure that should be the default behavior of the conda package.
