### ISSUE TITLE
Package needs a rebuild for latest conda-forge GCC?

### ISSUE THREAD

**Issue by parente** [conda-forge/nodejs-feedstock#59]
Not sure if this is the right place to file the issue, but trying to install jupyterhub today seemed to pull in `nodejs                    11.6.0            hf484d3e_1000` which relies on specific version of glib so's that are no longer installed for it. I vaguely recall a post somewhere that conda-forge is re-rendering for gcc7. Maybe this feedstock needs a re-render or to more explicitly declare its glib dependencies?

```
ESC[32m[I 2019-01-16 15:16:09.345 JupyterHub app:1453]ESC[m^O Hub API listening on http://127.0.0.1:8081/hub/
ESC[32m[I 2019-01-16 15:16:09.351 JupyterHub app:1176]ESC[m^O Starting proxy @ http://0.0.0.0:443/
node: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by node)
node: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by node)
node: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by node)
```

**Comment by minrk** [comment]
Hm. The latest builds on linux have been built with the new gcc7 compiler config. It's possible that they aren't doing it right?

**Comment by minrk** [comment]
How are you doing this install? Is it Docker? What base distro?

When I install this package (in `continuumio/miniconda3`), node works fine. Importantly, it shouldn't be loading libstdc++ from /usr/lib, it should be finding libstdc++ in the env:

```
(node) root@2a01fd70b211:/# ldd $CONDA_PREFIX/bin/node
	linux-vdso.so.1 (0x00007fffe60e2000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f86c701a000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f86c6e12000)
*	libstdc++.so.6 => /opt/conda/envs/node/bin/../lib/libstdc++.so.6 (0x00007f86c90c5000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f86c6b0e000)
	libgcc_s.so.1 => /opt/conda/envs/node/bin/../lib/libgcc_s.so.1 (0x00007f86c90b1000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f86c68f1000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f86c6552000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f86c8fea000)

(node) root@2a01fd70b211:/# conda list
# packages in environment at /opt/conda/envs/node:
#
# Name                    Version                   Build  Channel
libgcc-ng                 7.3.0                hdf63c60_0    conda-forge
libstdcxx-ng              7.3.0                hdf63c60_0    conda-forge
nodejs                    11.6.0            hf484d3e_1000    conda-forge
```

**Comment by parente** [comment]
Straight up conda install in a miniconda environment with the conda forge channel on an Ubuntu VM. I totally missed that it was looking in the root /usr instead of the prefix.

The VM isnt the freshest. What’s interesting is that forcing node back to 0.8.10 from conda forge in a separate conda env makes the problem go away. Therefore I assumed something wrong with the node build and not the environment. 

I’ll do some more hunting. If I can’t reproduce it elsewhere we can chalk it up to something about the VM and close the issue since it seems to be working for you.

**Comment by minrk** [comment]
The first things I'd check:

- `ldd $(which node)` to make sure it finds libstdc++ in the env,
- `$*PATH` vars to see if library loading is being customized

**Comment by parente** [comment]
I haven't been able to reproduce the problem. `ldd` shows libs in the conda environment and the environment variables look clean. I can't explain how it managed to look outside the environment for those libstdc++ files one time.
