### ISSUE TITLE
Not building on Windows

### ISSUE THREAD

**Issue by minrk** [conda-forge/nodejs-feedstock#65]
nodejs hasn't successfully built on Windows in some time. We now have two Windows CIs (AppVeyor and Azure), and neither can build nodejs with their free tier on Windows due to resource limitations. Currently, this is disk space, but it has been both time and memory in the past. Node.js appears to require more than 12GB of disk space to build from source on Windows, while AppVeyor and Azure give only 10.

I don't know how or if the build can use less disk space, or if there's a way to carefully split things across disks so that it fits. It seems astonishing that 12GB of intermediates are required to build a 13MB final product, but that appears to be the case. I don't know enough about Windows builds to chase down if there's something optional we can turn off to improve the build efficiency.

**Comment by minrk** [comment]
After #66, Windows releases are being published again, but we are not compiling it anymore.

**Comment by sodre** [comment]
@minrk, I am trying to build a `webpack` for conda-forge and I noticed that `node` and `npm` binaries are not in location that is automatically added to the `PATH` on Windows. Is there any reason why it needs to be done that way? If so could we add an activate/deactivate script which would add node/npm to the path?

**Comment by minrk** [comment]
That's strange. What's PATH when you `conda activate` an env? I don't have access to a Windows machine at the moment, but the recipe tests appear to verify that node and npm are on PATH.

**Comment by sodre** [comment]
I'm having problems on the build servers themselves. I think it might be because nodejs is already installed on them outside of the conda-process... I'll dig a little bit more and try to come with a better error report.

**Comment by wolfv** [comment]
I think this is fixed.
