### ISSUE TITLE
Request to package LTS nodejs releases

### ISSUE THREAD

**Issue by scottt** [conda-forge/nodejs-feedstock#67]
At work, we use the slower moving LTS nodejs releases, e.g. `10.15.1` on Linux and Mac OS.
This is a request to create a `10.x` branch for `nodejs-feedstock` and package the LTS releases.

**Comment by minrk** [comment]
@scottt makes sense! #70 should do it

**Comment by minrk** [comment]
Landed. Should be uploaded in an hour or two.
